version: "3.7"
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
#      - </path/to/audiobooks>:/audiobooks
#      - </path/to/podcasts>:/podcasts
      - ./config:/config
      - ./metadata:/metadata
