services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver
    volumes:
      - ./config:/config
      - ./downloads:/downloads #optional
      - ./incomplete-downloads:/incomplete-downloads #optional
    ports:
      - 8080:8080
    restart: unless-stopped
